### ISSUE TITLE
WebService cannot succesfully start on port 8081 in latest SF, SF SDK, VS 2017

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure-Samples/service-fabric-dotnet-web-reference-app#33]
I am using SF 2.6 and SF SDK 5.6 with VS 2017 15.3 Preview 4.0.

This is what I get in SF Explorer for the WebService:

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures in_Node_0 API call: IStatelessServiceInstance.Open(); Error = Microsoft.Net.Http.Server.WebListenerException (-2147467259)
The prefix 'http://+:8081/fabrikam/' is already registered.
   at Microsoft.Net.Http.Server.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
   at Microsoft.Net.Http.Server.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
   at Microsoft.Net.Http.Server.WebListener.Start()
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()

It does not matter which port I set in the config, BTW.
Any idea what could be the cause here?

**Comment by ChristianWeyer** [comment]
Well, this is just a warning - so all is fine ;-)

**Comment by davemckerral** [comment]
If you're running locally in 5-node mode then each of the nodes will be trying to assign that port on the same machine, so 4 of them won't succeed.
